"""
Auto-generated OData selectors and DTOs (combined file).
Generated on: 2025-11-26 13:56:59

DO NOT EDIT THIS FILE MANUALLY.
Regenerate using: python manage.py generate_odata_selector --single

Available options:
  --single   Generate one combined file instead of separate files
  --force    Overwrite existing files without prompting
"""

from __future__ import annotations  # Enable forward references

from dataclasses import dataclass

from django.apps import apps

from fc_selector.core.dtos import UNSET, BaseODataDTO
from fc_selector.django.selector import ODataSelector

Author = apps.get_model('blog', 'Author')
BlogPost = apps.get_model('blog', 'BlogPost')
Category = apps.get_model('blog', 'Category')
ContentType = apps.get_model('contenttypes', 'ContentType')
Group = apps.get_model('auth', 'Group')
Permission = apps.get_model('auth', 'Permission')
User = apps.get_model('auth', 'User')


# ==================== DTOs ====================

@dataclass
class UserDTO(BaseODataDTO):
    """DTO for User model."""
    id: str = UNSET
    password: str = UNSET
    last_login: str = UNSET
    is_superuser: bool = UNSET
    username: str = UNSET
    first_name: str = UNSET
    last_name: str = UNSET
    email: str = UNSET
    is_staff: bool = UNSET
    is_active: bool = UNSET
    date_joined: str = UNSET
    is_anonymous: str = UNSET  # @property
    is_authenticated: str = UNSET  # @property
    # pk: str = UNSET  # @property
    author: UserDTO | None = UNSET
    groups: list[GroupDTO] | None = UNSET
    user_permissions: list[PermissionDTO] | None = UNSET

@dataclass
class AuthorDTO(BaseODataDTO):
    """DTO for Author model."""
    id: str = UNSET
    bio: str = UNSET
    website: str = UNSET
    avatar: str = UNSET
    created_at: str = UNSET
    email: str = UNSET  # @property
    name: str = UNSET  # @property
    # pk: str = UNSET  # @property
    user: UserDTO | None = UNSET
    posts: list[BlogPostDTO] | None = UNSET  # Reverse relation

@dataclass
class BlogPostDTO(BaseODataDTO):
    """DTO for BlogPost model."""
    id: str = UNSET
    title: str = UNSET
    slug: str = UNSET
    content: str = UNSET
    excerpt: str = UNSET
    status: str = UNSET
    featured: bool = UNSET
    view_count: str = UNSET
    rating: float = UNSET
    created_at: str = UNSET
    updated_at: str = UNSET
    published_at: str = UNSET
    tags: list = UNSET
    metadata: dict = UNSET
    is_published: str = UNSET  # @property
    # pk: str = UNSET  # @property
    word_count: str = UNSET  # @property
    author: AuthorDTO | None = UNSET
    categories: list[CategoryDTO] | None = UNSET

@dataclass
class ContentTypeDTO(BaseODataDTO):
    """DTO for ContentType model."""
    id: str = UNSET
    app_label: str = UNSET
    model: str = UNSET
    app_labeled_name: str = UNSET  # @property
    name: str = UNSET  # @property
    pk: str = UNSET  # @property

@dataclass
class GroupDTO(BaseODataDTO):
    """DTO for Group model."""
    id: str = UNSET
    name: str = UNSET
    # pk: str = UNSET  # @property
    permissions: list[PermissionDTO] | None = UNSET

@dataclass
class PermissionDTO(BaseODataDTO):
    """DTO for Permission model."""
    id: str = UNSET
    name: str = UNSET
    codename: str = UNSET
    # pk: str = UNSET  # @property
    content_type: ContentTypeDTO | None = UNSET

@dataclass
class CategoryDTO(BaseODataDTO):
    """DTO for Category model."""
    id: str = UNSET
    name: str = UNSET
    description: str = UNSET
    created_at: str = UNSET
    # pk: str = UNSET  # @property


# ==================== SELECTORS ====================

class BlogPostSelector(ODataSelector):
    """Selector for BlogPost with DTO support."""

    class Meta:
        model = BlogPost
        dto_class = BlogPostDTO
        expandable_fields = {
            "author": AuthorDTO,
            "categories": CategoryDTO,
        }

class ContentTypeSelector(ODataSelector):
    """Selector for ContentType with DTO support."""

    class Meta:
        model = ContentType
        dto_class = ContentTypeDTO
        expandable_fields = {}

class GroupSelector(ODataSelector):
    """Selector for Group with DTO support."""

    class Meta:
        model = Group
        dto_class = GroupDTO
        expandable_fields = {
            "permissions": PermissionDTO,
        }

class PermissionSelector(ODataSelector):
    """Selector for Permission with DTO support."""

    class Meta:
        model = Permission
        dto_class = PermissionDTO
        expandable_fields = {
            "content_type": ContentTypeDTO,
        }

class AuthorSelector(ODataSelector):
    """Selector for Author with DTO support."""

    class Meta:
        model = Author
        dto_class = AuthorDTO
        expandable_fields = {
            "user": UserDTO,
            "posts": BlogPostDTO,  # Reverse relation from BlogPost.author
        }

class UserSelector(ODataSelector):
    """Selector for User with DTO support."""

    class Meta:
        model = User
        dto_class = UserDTO
        expandable_fields = {
            "author": UserDTO,
            "groups": GroupDTO,
            "user_permissions": PermissionDTO,
        }

class CategorySelector(ODataSelector):
    """Selector for Category with DTO support."""

    class Meta:
        model = Category
        dto_class = CategoryDTO
        expandable_fields = {}
